#!/bin/sh


SERVICE="sshd"

if systemctl is-active --quiet "$SERVICE"; then
    notif_send 2 "Kill SSH" "" ""
    pkexec systemctl stop "$SERVICE"
    notif_send 2 "SSH has benn Killed" "" "skull"
else
    notif_send 2 "Start SSH" "" ""
    pkexec systemctl start "$SERVICE"
    notif_send 2 "SSH has benn Started" "" "check"
fi
