#!/bin/sh

SETTINGS="/etc/pure-ftpd/pure-ftpd.conf"

notif_send 0 "PURE_FTP: TLS 1" "Accept both cleartext and encrypted sessions." "check"

kitty sudo sed -i "s/TLS 2/TLS 1/" "$SETTINGS" &
sudo systemctl restart pure-ftpd
