#!/bin/sh

SETTINGS="/etc/pure-ftpd/pure-ftpd.conf"

notif_send 0 "PURE_FTP: TLS 2" "Refuse connections that don't use the TLS security mechanism, including anonymous sessions." "check"
kitty sudo sed -i "s/TLS 1/TLS 2/" "$SETTINGS" &
sudo systemctl restart pure-ftpd
