#!/bin/bash

if pgrep -x "mako" > /dev/null; then
  pkill -x mako
  notify-send --icon="/home/arc/.config/custom_images/kill.png" "Mako has been KILLED!!!"
  sleep 0.1
fi
if pgrep -x "waybar" > /dev/null; then
  pkill -x waybar
  notify-send --icon="/home/arc/.config/custom_images/kill.png" "Waybar has been KILLED!!!"
  sleep 0.5
fi


hyprctl reload
notify-send  --icon="/home/arc/.config/custom_images/good_job.png" "Mako Reloaded"
notify-send  --icon="/home/arc/.config/custom_images/good_job.png" "Hyprland Reloaded"

notify-send  --icon="/home/arc/.config/custom_images/good_job.png" "Waybar Started"
waybar &
