#!/bin/sh

choice=$(printf "L -> Lock\nE -> Logout\nS -> Shutdown\nR -> Reboot\nX -> Suspend" | wmenu -N 000000ff -n ffffffff -S ffffffff -s 000000ff -M 000000ff -m 999999ff -p 'Powermenu >'  -l 39 -f 'JetBriansMono NF 12' -i)

case "$choice" in
    "L -> Lock")     swaylock ;;
    "E -> Logout")   pkill -x dwl ;;
    "S -> Shutdown") systemctl poweroff ;;
    "R -> Reboot")   systemctl reboot ;;
    "X -> Suspend")  systemctl suspend ;;
esac