#!/usr/bin/env fish
# moon-face-print

set FILE $HOME/.config/myscripts/moon-face/moon-face-char

# mode 1 outline characters
# mode 2 simple characters
set MODE 2

# soth 0 = starts at right side
# soth 1 = starts at left side
set SOUTH 0
# set south to 0 if u are in north of the Earth
# set south to 1 if u are in south of the Earth

sed -n (math "$SOUTH * 2 + $MODE")p $FILE
