#!/usr/bin/env fish

set MOON_FILE $HOME/.config/myscripts/moon-face/moon-face-char

set year (date +%Y)
set month (date +%m)
set day (date +%d)

set a (math "floor((14 - $month)/12)")
set y (math "$year + 4800 - $a")
set m (math "$month + 12*$a - 3")
set jdn (math "$day + floor((153*$m + 2)/5) + 365*$y + floor($y/4) - floor($y/100) + floor($y/400) - 32045")

# 2451550.1 = Julian Date
set phase (math "floor(($jdn - 2451550.1) % 29.530588853)")
set phase (math "$phase + 1")

set lineNorth1                             
set lineNorth2                             

set lineSouth1                             
set lineSouth2                             

set charN1 $lineNorth1[$phase]
set charN2 $lineNorth2[$phase]

set charS1 $lineSouth1[$phase]
set charS2 $lineSouth2[$phase]

#echo "$phase"
echo "$charN1" >$MOON_FILE
echo "$charN2" >>$MOON_FILE
echo "$charS1" >>$MOON_FILE
echo "$charS2" >>$MOON_FILE
