#!/usr/bin/env fish

set hour (date +%H)

# mode 1: outline chars
# mode 2: simple chars
set mode 2

if test $mode -eq 1
    set chars "󱑖" "󱑋" "󱑌" "󱑍" "󱑎" "󱑏" "󱑑" "󱑐" "󱑒" "󱑓" "󱑔" "󱑕"
else
    set chars "󱑊" "󱐿" "󱑀" "󱑁" "󱑂" "󱑃" "󱑄" "󱑅" "󱑆" "󱑇" "󱑈" "󱑉"
end

set index (math "$hour % 12 + 1")

echo "$chars[$index] $hour:$(date +%M)"
